# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52c8c0c8ce187f47af528169f01b774a8105d235897efe5e368349fd2e6472fbfa69a7596b2a8b22a68a141fa9a58943a4489f53be99fdf4280d76634a27258c

test:
  secret_key_base: d552784e707ff764891d4b2e6b3b09ba7295ad8ba4af05e6e7fe6e1a5121949430255d7f2a7aefc178603c2cd990471f567fe27e4b98be8f4e5ebd18ec21cdd5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
